hashicorp-forge/grove

- .github/workflows/documentation.yml
- .github/workflows/release.yml
- templates/deployment/local-quick-start/Dockerfile
- templates/deployment/local-quick-start/test_entrypoint.sh
This pull-request temporarily removes Docker image building and publishing, and adds a new workflow which allows for the manual deployment of documentation from an existing tagged version.
Finally, this pull-request resolves an incorrect reference in the quick-start Dockerfile.
> Temporarily remove Docker publish. Add documentation publish.

- grove/caches/aws_dynamodb.py
- grove/configs/aws_ssm.py
- grove/configs/local_file.py
- grove/connectors/github/audit_log.py
- grove/connectors/gsuite/activities.py
- grove/outputs/aws_s3.py
- grove/outputs/local_file.py
- grove/secrets/aws_ssm.py
- grove/secrets/hashicorp_vault.py
- templates/configuration/github/enterprise_audit_log.json
- templates/configuration/github/orgs_audit_log.json
- templates/configuration/github/self-hosted_orgs_audit_log.json
- templates/configuration/gsuite/activities.json
Per the feedback provided in #17, Google publishes estimate lag times for activity types. Collection of new log entries inside of this lag window often results in missed log entries - as the data is not yet considered consistent by the vendor.
During investigation, this was also discovered to be the case with GitHub audit logs, albeit at a much lower rate. 
As an interim work around while a more robust periodic retrospection and de-duplication process is implemented, a set of delay configuration parameters have been added to the connectors known to be affected by this sort of consistency lag.
This configuration parameter allows operations to preference consistency over collection time. As this is defined in the connector configuration, this may be specified per operation type, allowing …
> Add configurable delay for Google and Github.

- grove/__about__.py
- grove/connectors/onepassword/api.py
- grove/connectors/onepassword/events_audit.py
- setup.py
- templates/configuration/1password/events_audit.json
- tests/fixtures/onepassword/events_audit/001.json
- tests/fixtures/onepassword/events_audit/002.json
- tests/fixtures/onepassword/events_audit/003.json
- tests/test_connectors_onepassword_events_audit.py
Currently Grove has an onepassword connector. This PR adds the new Onepassword audit log feature.
API documentation: https://developer.1password.com/docs/events-api/reference/
> add onepassword audit log connector

- setup.cfg
This pull-request temporarily pins the version of `urllib3` to resolve incompatibility with the `google-auth` package.
> Pin `urllib3` due to `google-auth` incompatibility

- README.md
Add better dark mode support to the readme like described here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
> Add dark mode support to readme

- grove/connectors/github/api.py
- tests/test_connectors_github_audit.py
This pull request ensures that both HTTP 403s responses with `x-ratelimit-remaining: 0`, as well as HTTP 429s are handled for rate limiting.
This deviates from Github's [existing documentation](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit), which states that HTTP 403s will be used with `x-ratelimit-*` headers. However, recent rate-limit blog posts from Github mention that [HTTP 429](https://github.blog/changelog/2023-07-03-new-rate-limit-is-coming-for-the-audit-log-api-endpoints/) will be used.
Speaking with Github, they have advised that both should be handled.
> Handle HTTP 429s from Github.

- grove/__about__.py
- grove/connectors/__init__.py
- grove/processors/filter_entries.py
- pyproject.toml
- tests/fixtures/github/git/001.json
- tests/test_processors_filter_entries.py
This processor allows entire log entries to be filtered from output. This is intended to assist with reducing output "noise" from vendors who do not allow filtering of audit events in a way that allows their customers to exclude certain events. This is especially useful for vendors such as Github, where Git audit events will contain log entries for interactions against public Git repositories by all Github users - but without actor information provided in these entries.
This pull-request also adjusts the log in the processor handler to allow additions and removals of entire log entries during processing, rather than just additions.
> [1.1.0] Add new `filter_entries` processor

- grove/__about__.py
- grove/connectors/atlassian/api.py
- tests/test_connectors_atlassian_audit_events.py
Atlassian have a number of rate-limiters which differ depending on the API. This commit ensures that the rate-limit handler for the Admin API operates as expected.
> Fix up Atlassian rate-limiting.

- grove/__about__.py
- grove/connectors/__init__.py
This pull-request modifies connector exception messages to include the connector "kind" which has failed to execute. This is in order to improve handling in APM / Observability tools, preventing errors from all connectors from being 'stacked' where the tool does not support differentiation based on the 'extra' information provided from the error level logs.
> [1.2.1] Improve errors in failure cases.

- grove/connectors/okta/api.py
- grove/connectors/oomnitza/api.py
- tests/test_connectors_oomnitza_activities.py
This pull-request adjusts the Oomnitza page-size to ensure that collection can complete in a timely manner during large integration runs. Additionally, this pull-request fixes a typo in the Okta rate-limit handler to ensure that rate-limits are correctly handled.
> [v1.2.2] Fix Oomntiza pagination size, Okta rate-limiting

- .github/workflows/ci.yml
- grove/__about__.py
- grove/helpers/plugin.py
- pyproject.toml
- tests/test_connectors_gsuite_activities.py
- tests/test_connectors_gsuite_alerts.py
This pull-request adds support for Python 3.12. It also resolves current issues with tests failing for the Google Workspace connectors after a change in the Google SDK.
> [1.3.0] Add Python 3.12 support. Fix Google tests.

- grove/__about__.py
- grove/connectors/gsuite/alerts.py
This pull request increases the number of alerts returned by Google Workspace Alerts per page.
This is a temporary mitigation for a strange error encountered with the Google Workspace API where pagination returns 400 errors, despite the requests being performed using the pagination token returned by the API, and using the official Google Python SDK.
We will look to open a bug report with Google around this behaviour.
> [1.3.1] Increase Google Workspace Alert page size

- grove/__about__.py
- grove/helpers/parsing.py
- grove/outputs/remote_http.py
- pyproject.toml
- tests/test_outputs_remote_http.py
This pull-request adds an initial remote HTTP output handler. This output handler allows collected logs to be submitted to a configured HTTP / HTTPS endpoint via HTTP POST in ND-JSON format.
Additionally, this pull-request resolves a small bug in the the `filter_paths` processor, which raises a KeyError when a configured path to drop does not exist. This is a minor bug which only occurs in very specific configurations.
This pull-request is in response to the ask from #47.
In order to maximise compatibility, this handler provides the following configuration options:
* `GROVE_OUTPUT_REMOTE_HTTP_URL`
* **Description**: The URL to POST collected logs to.
* **Example**: `https://192.0.2.1/some/endpoint`
* `GROVE_OUTPUT_REMOTE_HTTP_HEADERS`
* **Description**: An optional set of pipe ('|') …
> [1.4.0] Add remote HTTP output handler.

- .github/workflows/ci.yml
- Dockerfile
- docker-compose.yml
- templates/deployment/local-quick-start/Dockerfile
When [following the instructions in the project README](https://github.com/hashicorp-forge/grove?tab=readme-ov-file#quick-start) to `docker compose up` to get started, I experienced a few build and run issues. These appear to be related to the [infamous compatibility inconsistencies with python projects and docker alpine images](https://pythonspeed.com/articles/alpine-docker-python/). I took a pass at remedying the issue by switching the images to python:3.9-slim and switching the docker compose to reference the root dockerfile, and this fixed the build and runtime issues getting started with Grove.
- Migrates docker images from alpine to python:3.9-slim due to build failures caused by wheels incompatibility in the alpine based images
- Updates docker compose to use main Dockerfile due to …
> fix: migrates docker images to python:3.9-slim

- grove/caches/local_file.py
- pyproject.toml
- tests/test_caches_local_file.py
This pull-request adds a local file backed cache handler.
This enables much easier local testing of connectors, and can be used to enable "one-shot" style use by analysts during incident response. This works by caching the values locally in flat files, allowing Grove to read back these files and understand where the last collection was up to.
As there is no locking, this should likely not be used in production, but it may be used in a pinch if required.
> Add local file backed cache handler.

- Dockerfile
Per the feedback from #52 , this pull-request moves the Dockerfile to installing Grove from the currently checked out sources, rather than the released version from PyPi.
This also moves the container to Python 3.12 by default.
> Move Dockerfile to build current source, rather than release.

- grove/connectors/tines/api.py
- tests/fixtures/tines/audit_logs/001.json
- tests/fixtures/tines/audit_logs/002.json
- tests/fixtures/tines/audit_logs/003.json
This pull-request resolves a bug reported by @britton-from-notion in #52. This has been validated to resolve the reported issue in a local reproduction environment.
> Basically, it's a silly bug where the page number is being incorrectly set to the value of next_page rather than next_page_number - where one is a URI, and the other is an integer.
>
> As a result, we're passing a URI to the page directive of the Tines API, rather than just an integer. Looking at my old test fixtures, it appears that this next_page_number field is "new", but it appears that the next_page field was always a URI so it was still an error in the connector. We just never triggered it as the event load when using the connector was always less than 500-events per run interval.
>
> Unfortunately, it seems like the …
> 🐛 Fix pagination bug in Tines connector (related to #52).

- README.md
- docs/index.rst
- grove/__about__.py
- grove/connectors/snowflake/common.py
- grove/connectors/snowflake/login_history.py
- grove/connectors/snowflake/query_history.py
- grove/connectors/snowflake/session_history.py
- grove/models.py
This pull-request allows users to specify the schema and database for the Snowflake connector. It also increases the number of records per batch to 1000, and reduces the amount of data collected from `QUERY_HISTORY` for the first time to the last hour only.
This is due to the volume of data present in this table usually being very high, so auditing will only effectively start from the time that Grove is first deployed.
Finally, this pull-request allows the use of internal Pydantic field names in connector configuration documents. This is required due to the new `schema` field name - which is the name of a method internal to Pydantic. This is a hack, which can be removed once we update Grove to Pydantic >= 2.
> Allow specification of Snowflake schema and database

- grove/connectors/dropbox/team_events.py
- tests/fixtures/dropbox/team_events/002.json
- tests/test_connectors_dropbox_team_events.py
It appears that Dropbox Team Events are returned in chronological order. This is good news, save for that the current implementation was based on them being in reverse chronological order - which is incorrect.
> 🐛 Dropbox Team Events are in chronological order

- grove/connectors/onepassword/api.py
- grove/connectors/onepassword/events_audit.py
- grove/connectors/onepassword/events_itemusages.py
- grove/connectors/onepassword/events_signinattempts.py
- grove/connectors/onepassword/util.py
- tests/test_connectors_onepassword_events_audit.py
- tests/test_connectors_onepassword_events_itemusages.py
- tests/test_connectors_onepassword_events_signinattempts.py
- tests/test_connectors_onepassword_util.py
1Password documents that the cursor should be used for pagination: https://developer.1password.com/docs/events-api/reference/#pagination with only the initial request based on timestamp.
Previously, this used a timestamp and we found that events would get lost because 1Password follows a model of eventual consistency so getting the events for a current timestamp and then getting events for a timestamp at some point in the future may miss events that occurred before that timestamp but did not actually come in until after.
See: https://github.com/hashicorp-forge/grove/issues/64
> Issue 64: Update Grove to use cursor for 1Password instead of Timestamp

- grove/__about__.py
- grove/connectors/pagerduty/audit_records.py
This pull-request fixes up the default pointer for PagerDuty, which uses a different date-time format than was defined. This only affects the first ever collection, so this change should not impact existing users.
> Fix default PagerDuty pointer

- grove/connectors/zitadel/__init__.py
- grove/connectors/zitadel/events.py
- pyproject.toml
- templates/configuration/zitadel/zitadel_events_user.json
- tests/test_connectors_zitadel_events.py
This PR adds a custom connector for retrieving events using the [Zitadel Events API](https://zitadel.com/docs/guides/integrate/zitadel-apis/event-api) for the authentication management service, [Zitadel](https://zitadel.com/)
- You will need to know which [Aggregate Event Types]([AggregateTypesList](https://zitadel.com/docs/apis/resources/admin)) to query for and use these in the `"aggregate_event_types"` field in the configuration object
- You will need to enter the FQDN for your Zitadel instance for the the `identity` field in the configuration object
> Zitadel connector

- grove/__about__.py
- grove/connectors/tfc/api.py
This pull-request ensures that the TFC connector will attempt to retry a finite number of times, and will honor the reset timer from the TFC API.
> Constrain rate-limits for TFC connector.

- grove/caches/aws_dynamodb.py
- grove/caches/local_file.py
- grove/caches/local_memory.py
- grove/entrypoints/local_daemon.py
This pull-request genericises the exception handler in the `groved` event loop in order to ensure unhandled exceptions don't bubble up and and kill the main event loop.
This also moves a number of lo messages to debug to avoid confusion when reviewing logs.
> Move debug log messages to debug. Genericise exception handlers.

- grove/__about__.py
- grove/connectors/__init__.py
- grove/entrypoints/base.py
- grove/entrypoints/local_daemon.py
- grove/helpers/parsing.py
- grove/outputs/local_stdout.py
- grove/outputs/remote_http.py
- grove/processors/extract_paths.py
- tests/fixtures/grove/reverse_chronological/003.json
This pull-request attempts to resolve #80 and #81, including:
* Fixes silly bug related to use of seconds vs total_seconds in dispatch.
* Fixes default serialisation prior to adding common serialiser (#85).
* Makes sure deduplication hash cache doesn't grow infinitely on massive collections.
* Ensures pointer deduplication operates the same way between chronological and reverse chronological ordering.
> 🐛 Fix up retry logic on connector failures, various other bug fixes.

- grove/connectors/tfc/api.py
- tests/test_connectors_tfc_audit_trails.py
TFC returns a string representing a float in the rate-limit reset header(s). This pull-request ensures that we cast to a `float` before passing to `int` to avoid `ValueErrors`.
> 🐛 TFC: Cast to float before int

- grove/connectors/gsuite/usage.py
Recent commit [273ea68](https://github.com/hashicorp-forge/grove/commit/273ea686c6df3bab9c76637ce72414c94b86eee4) introduced Google Workspaces (GSuite) connector for Entity, User, and Customer Usage reports. 
In feedback, we decided to enforce setting a timezone (UTC) to be used in calculating and paginating using pointer (date). However, we failed to note that the current logic doesn't instantiate a `start_date` using UTC time on the first run. This will lead to `TypeError: can't compare offset-naive and offset-aware datetimes` when attempting to compare offset-naive pointer dates with the offset-aware pointer.
This bugfix adds UTC time to the `start_date`, which allows for pagination.
> add utc timezone to start_date

- grove/connectors/google/bigquery_query.py
- grove/connectors/google/utils.py
- tests/test_connectors_google_bigquery_query.py
- tests/test_connectors_google_utils.py
- Adds another bugfix to the google bigquery connector
- We were using this to retrieve [Gmail logs stored in bigquery ](https://support.google.com/a/answer/12384955?hl=en&src=supportwidget0&authuser=0) and, although the connector worked for some time and would retrieve and paginate logs, after some time we would see errors that the date for the pointer became out of range
- Looking back at our logic for declaring and updating the pointer, we realized that the `event_info.timestamp_usec` field is actually in microseconds - *not* milliseconds
- Rather than make one small fix to update this logic, we refactored the connector to use a microseconds conversion helper function, while keeping the ability to use a milliseconds function and also added a seconds function. This modular approach …
> refactor bigquery connector and add tests

- grove/connectors/google/bigquery_query.py
- tests/test_connectors_google_bigquery_query.py
This PR adds `max_batches` logic to Google Bigquery connector to allow the connector to save a batch of logs (default `3`) and exit, allowing other connectors to run.
This was after we noticed in our deployment that the connector would run continuously, saving a large volume of logs without catching up or incrementing the pointer (due to the pagination loop). During this time CPU utilization significantly dropped while memory utilization increased by roughly 10%
What was more surprising to us was that other connectors would fail to start during this process, effectively blocking all other pipelines/connectors.
- Deployment: `local_process` via AWS ECS
- Output: AWS S3
- Cache: AWS DynamoDB
- Config: AWS SSM Parameter Store
It would be helpful for us to understand: Grove appears to be …
> bugfix: add max_batches logic

- grove/connectors/google/bigquery_query.py
- tests/test_connectors_google_bigquery_query.py
- **Fixed `max_batches` configuration error**
- The connector currently works with `max_batches` set, but will error out if it is not set due to the placement of the logic for default value. This PR fixes that issue.
- **Updated query logic**: Replaced `_PARTITIONTIME` (which is not included on all bigquery tables) in the SQL query with the actual user-defined timestamp field specified in `POINTER_PATH`
> Bigquery max batches fix

- grove/connectors/__init__.py
This pull-request enables the base connector to select and use the `window_end` value in place of the `pointer` when windowing is in use, and there is a `window_end` value in the cache. This is in order to ensure that logs are not recollected between collections, which should provide a speed up and prevent duplicate log record collection.
These code paths should only ever be hit in `REVERSE_CHRONOLOGICAL` mode - as windowing is not used outside of this mode.
> Feature: Use `window_end` as pointer when set.

- grove/connectors/google/bigquery_query.py
- grove/connectors/google/utils.py
- templates/configuration/google/bigquery.json
- templates/configuration/google/bigquery_gmail.json
- tests/test_connectors_google_bigquery_query.py
- `max_batches` configuration: Changed from direct attribute access to getattr() with default value of 3
- Optimized SQL syntax: Uses only the user-specified `pointer_path` for queries
- Added support for timestamp as well as epoch microseconds formats for `pointer_path`
- `time_format` is now a mandatory field
> Time Format feature for Google BigQuery connector

- grove/connectors/google/bigquery_query.py
- tests/test_connectors_google_bigquery_query.py
- Fixed microseconds format to use numeric comparison instead of timestamp strings
- Enhanced pointer handling for nested JSON structures
- Added proper error handling for invalid pointer formats
- Added exponential backoff if deadlock related errors are thrown
- Added additional test cases
> bugfix: Bigquery timestamp conversion update

- README.md
- docs/index.rst
- grove/connectors/launchdarkly/__init__.py
- grove/connectors/launchdarkly/api.py
- grove/connectors/launchdarkly/audit_records.py
- pyproject.toml
- templates/configuration/launchdarkly/audit_records.json
- tests/fixtures/launchdarkly/audit_log_item_1.json
- tests/fixtures/launchdarkly/audit_log_item_2.json
- tests/fixtures/launchdarkly/audit_log_item_3.json
- tests/fixtures/launchdarkly/audit_log_item_4.json
- tests/fixtures/launchdarkly/audit_log_item_5.json
- tests/fixtures/launchdarkly/audit_log_item_6.json
- tests/fixtures/launchdarkly/audit_log_list_1.json
- tests/fixtures/launchdarkly/audit_log_list_2.json
- tests/fixtures/launchdarkly/audit_log_list_3.json
- tests/test_connectors_launchdarkly_audit_records.py
Creating a LaunchDarkly Audit Log connector.
The connector first pulls the list of audit log entries from the API endpoint 
https://launchdarkly.com/docs/api/audit-log/get-audit-log-entries
After, it iterates through the IDs of the entries and returns the more detailied information about each entry using the API endpoint
https://launchdarkly.com/docs/api/audit-log/get-audit-log-entry
> Add Launchdarkly Audit Log Connector

- grove/connectors/sf/event_log.py
- tests/test_connectors_sf_event_log.py
Replaces klaviyo.salesforce.com references with testorg.my.salesforce.com in test files and comments to ensure all test data uses obviously fake values.
- Updated comment example in `grove/connectors/sf/event_log.py`
- Replaced klaviyo references in `tests/test_connectors_sf_event_log.py` test cases
- All test data now uses `testorg.my.salesforce.com` instead of `klaviyo.my.salesforce.com`
- `grove/connectors/sf/event_log.py` - Updated comment example
- `tests/test_connectors_sf_event_log.py` - Updated test instance URLs and assertions
> Fix klaviyo references in test files
